services:
    - type: web
      name: frontend
      runtime: static
      repo: https://github.com/ktatu/apextourneystreams-frontend.git
      region: frankfurt
      branch: main
      buildCommand: npm run build
      staticPublishPath: ./build
      rootDir: src
