/*
This file has been AI generated by GitHub Copilot.
*/

import { parseString } from "./parseHelpers.js"

const parseProfileImageUrls = (rawData: unknown): Map<string, string> => {
    const profileImageUrls = new Map<string, string>()

    if (!(rawData instanceof Array)) {
        throw new Error("Unexpected response data format")
    }

    rawData.forEach((rawData) => {
        if (!rawData || typeof rawData !== "object") {
            throw new Error("Unexpected response data format")
        }
        if (!("login" in rawData) || !("profile_image_url" in rawData)) {
            throw new Error("Unexpected response data format")
        }

        profileImageUrls.set(
            parseString(rawData.login, "login"),
            parseString(rawData.profile_image_url, "profile_image_url"),
        )
    })

    return profileImageUrls
}

export default parseProfileImageUrls
