// AI-generated by Claude Sonnet 5: refactored to requireEnv/optionalEnv helpers so required-ness is declared alongside each variable, replacing the separate requiredEnvVars list.
import "dotenv/config"

const missingEnvVars: string[] = []

const requireEnv = (key: string): string => {
    const value = process.env[key]

    if (!value) {
        missingEnvVars.push(key)
    }

    return value as string
}

const optionalEnv = (key: string): string | undefined => process.env[key]

export const TWITCH_CLIENT_ID = requireEnv("TWITCH_CLIENT_ID")
export const TWITCH_CLIENT_SECRET = requireEnv("TWITCH_CLIENT_SECRET")
export const TWITCH_CALLBACK_URL = requireEnv("TWITCH_CALLBACK_URL")

export const JWT_SECRET = requireEnv("JWT_SECRET")
export const NODE_ENV = optionalEnv("NODE_ENV")

export const REDIS_URL = requireEnv("REDIS_URL")
export const REDIS_USERNAME = requireEnv("REDIS_USERNAME")
export const REDIS_PASSWORD = requireEnv("REDIS_PASSWORD")
export const REDIS_HOST = requireEnv("REDIS_HOST")
export const REDIS_PORT = parseInt(requireEnv("REDIS_PORT"))

export const YOUTUBE_API_KEY = requireEnv("YOUTUBE_API_KEY")

export const CLIENT_URL = requireEnv("CLIENT_URL")

if (missingEnvVars.length > 0) {
    missingEnvVars.forEach((key) => console.warn(`Env variable ${key} has not been set`))
}
