name: Continuous integration & deployment

on:
  push:
    branches:
    - main
    paths:
    - "src/**"
  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  publish_image:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ktatu/tourneystreams
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
  deploy_image:
    needs: publish_image
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deployment
      uses: fjogeleit/http-request-action@eab8015483ccea148feff7b1c65f320805ddc2bf
      with:
        url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        method: "GET"
